name: build-solution

on:
  workflow_call:
    inputs:
      solution_name:
        required: true
        type: string

jobs:
  build-solution:
    runs-on: ubuntu-latest

    env:
      solution_pack_folder: solution-pack-temp
      build_number: 1.0.${{ github.run_number }}

    steps:
      - uses: actions/checkout@v2

      - name : clear out solution version number
        shell: pwsh
        run: |
          $solutionName = '${{ github.event.inputs.solution_name }}'
          Get-ChildItem -Path "/src/$solutionName/SolutionPackage/**/Solution.xml" | 
          ForEach-Object {
                (Get-Content $_.FullName) `
                    -replace '<Version>[\s\S]*?<\/Version>', '<Version>${{ env.build_number }}</Version>' |
                Out-File $_.FullName
          }

      - name: pack solution
        uses: microsoft/powerplatform-actions/pack-solution@0.4.3
        with:
          solution-folder: src/${{ inputs.solution_name }}/SolutionPackage
          solution-file: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ inputs.solution_name }}.zip
          solution-type: Managed
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.solution_name }}
          path: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ inputs.solution_name }}.zip
      
      