name: build-deploy-solution
# TODO: Makes sure this gets associated with the PR

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: "ref to build from"
      solution_name:
        required: true
        description: "solution to build"
      solution_version_major_minor:
        required: true
        description: "version major.minor of solution to build"
      environment:
        required: true
        description: "environment where the build will be deployed"

jobs:
  update-pr-with-link-to-workflow:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          echo "${{ github.run_id }}"
          $ref = "${{ github.event.inputs.ref }}"
          if ($ref.Contains("refs/pull")) {
            echo $ref.Replace("refs/pull","").Replace("/merge","")
          }          
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  build-solution:
    name: build solution
    uses: devkeydet/pva-alm/.github/workflows/build-solution.yml@main
    with:
      ref: ${{ github.event.inputs.ref }}
      solution_name: ${{ github.event.inputs.solution_name }}
      solution_version_major_minor: "${{ github.event.inputs.solution_version_major_minor }}"

  deploy-solution:
    name: deploy solution to ${{ github.event.inputs.environment }} environment
    uses: devkeydet/pva-alm/.github/workflows/deploy-solution.yml@main
    needs: build-solution
    with:
      solution_name: ${{ github.event.inputs.solution_name }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      environment_url: ${{ secrets.ENVIRONMENT_URL }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
      deploymentsettings_tokens: ${{ secrets.PVAALM_DEPLOYMENTSETTINGS_TOKENS }}
