name: deploy-solution

on:
  workflow_call:
    inputs:
      solution_name:
        required: true
        type: string
      environment_url:
        required: false
        type: string
      tenant_id:
        required: true
        type: string
      client_id:
        required: true
        type: string
      client_secret:
        required: true
        type: string
     

jobs:
  deploy-solution:
    runs-on: ubuntu-latest

    env:
      solution_pack_folder: solution-pack-temp

    steps:
      - name: set environment to uat
        run: |
          echo 'environment_url=${{ inputs.uat_env }}' >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/main')
      
      - name: set environment to pr validation
        run: |
          echo 'environment_url=${{ inputs.pr_validation_env }}' >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/main') == false
      
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.solution_name }}
          path: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ inputs.solution_name }}.zip

      # comment
      - name: import solution to environment
        uses: microsoft/powerplatform-actions/import-solution@0.4.3
        with:
          environment-url: ${{ inputs.environment_url }}          
          tenant-id: ${{ inputs.tenant_id }}
          app-id: ${{ inputs.client_id }}
          client-secret: ${{ inputs.client_secret }}
          solution-file: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ inputs.solution_name }}.zip
          force-overwrite: true