name: deploy-solution

on:
  workflow_call:
    inputs:
      solution_name:
        required: true
        type: string
    secrets:
      environment_url:
        required: true
      tenant_id:
        required: true
      client_id:
        required: true
      client_secret:
        required: true

jobs:
  deploy-solution:
    runs-on: ubuntu-latest

    env:
      dkdt_PVAMSNWeather: ${{ secrets.PR_DKDT_PVAMSNWEATHER }}

    steps:      
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.solution_name }}
      
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["src/${{ inputs.solution_name }}/deploymentSettings.json"]'
        
      - name: import solution to environment
        uses: microsoft/powerplatform-actions/import-solution@0.4.3
        with:
          environment-url: ${{ secrets.environment_url }}          
          tenant-id: ${{ secrets.tenant_id }}
          app-id: ${{ secrets.client_id }}
          client-secret: ${{ secrets.client_secret }}
          solution-file: ${{ inputs.solution_name }}.zip
          force-overwrite: true
          #deploymentSettings.json support coming soon
