name: deploy-solution

on:
  workflow_call:
    inputs:
      solution_name:
        required: true
        type: string
    secrets:
      ENVIRONMENT_URL:
        required: true
      TENANT_ID:
        required: true
      CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true     

jobs:
  deploy-solution:
    runs-on: ubuntu-latest

    env:
      solution_pack_folder: solution-pack-temp

    steps:      
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.solution_name }}
          path: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ inputs.solution_name }}.zip

      # comment
      - name: import solution to environment
        uses: microsoft/powerplatform-actions/import-solution@0.4.3
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}          
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ inputs.client_id }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-file: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ inputs.solution_name }}.zip
          force-overwrite: true