name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the Solution in Dataverse environment'
        required: true
        default: pvaalm
      environment_url:
        description: 'http endpoint of your Dataverse environment'
        required: true
        default: 'https://[your-env].crm.dynamics.com'
      solution_exported_folder:
        description: 'folder name for staging the exported solution'
        required: true
        default: out/exported-temp/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in'
        required: true
        default: out/unpack-temp/
      solution_target_folder: 
       description: 'folder name to be created and checked in'
       required: true
       default: src/SolutionPackage/${{ github.event.inputs.solution_name}}
env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  TENANT_ID: '${{ secrets.TENANT_ID }}

jobs:
  export-from-dev:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.3
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
