name: git-diff-test

on:
  push:
    branches:
      - main
    paths:
      - git-diff-test/**
jobs:
  determine-solution-build-deploy: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done