name: import-unmanaged-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: yoursolutionname
      environment_url:
        description: "http endpoint of your Dataverse environment"
        required: true
        default: "https://[your-env].crm[x].dynamics.com"
      ref:
        description: "the ref (branch, commit, tag) you want to import"
        required: true
        default: "main"

jobs:
  get-subdomain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get-subdomain
        uses: ./.github/actions/get-subdomain
        with:
          url: ${{ github.event.inputs.environment_url }}
    outputs:
      subdomain: ${{ steps.get-subdomain.outputs.subdomain }}

  build-solution:
    uses: devkeydet/pva-alm/.github/workflows/zz-r-build-solution.yml@main
    with:
      ref: ${{ github.event.inputs.ref }}
      solution_name: ${{ github.event.inputs.solution_name }}
      solution_version_major_minor: "0.0"
      dev_build: true

  deploy-solution:
    uses: devkeydet/pva-alm/.github/workflows/zz-r-deploy-solution.yml@main
    needs: [build-solution,get-subdomain]
    with:
      solution_name: ${{ github.event.inputs.solution_name }}
      environment: ${{ needs.get-subdomain.outputs.subdomain }}
      unmanaged: true
    secrets:
      environment_url: ${{ github.event.inputs.environment_url }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
