
name: iterate
on:
  workflow_dispatch:

jobs:
  iterate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        shell: pwsh
        run: | 
          $secrets = ConvertFrom-Json '${{ toJSON(secrets) }}'
          $props = Get-Member -InputObject $secrets -MemberType Properties
          $props = $props | Where-Object{!$_.Name.Equals("github_token")}
          $prop = $props[0].Name
          $secrets.$prop
