
name: iterate
on:
  workflow_dispatch:

jobs:
  iterate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Firenza/secrets-to-env@v1.1.0
        with:
            secrets: ${{ toJSON(secrets) }}
            secret_filter_regex: PR_*
      - name: echo
        shell: pwsh
        run: |
          echo ${{ env.PR_DKDT_PVAMSNWEATHER }}
