name: list-tag-by-commit

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'provide the tag'

jobs:
  list-tag-by-commit:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - run: |
          git fetch --all --tags
          $commit = git rev-list -n 1 tags/${{ github.event.inputs.tag }}
          echo "commit=$commit" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - run: |
          echo "${{ env.commit }}"