name: pvaalm-pr-main-build-deploy

env:
  solution_name: pvaalm

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**
  push:
    branches:
      - main
    paths:
      - src/pvaalm/**

jobs:
  build-solution:
    uses: devkeydet/pva-alm/.github/workflows/build-solution.yml@main
    with:
      solution_name: ${{ env.solution_name }}
  
  deploy-solution:
    uses: devkeydet/pva-alm/.github/workflows/deploy-solution.yml@main
    needs: build-solution
    with:
      solution_name: ${{ env.solution_name }}