name: pvaalm-pr-main-build-deploy
# Run a build and validate deployment on pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**
  push:
    branches:
      - main
    paths:
      - src/pvaalm/**

jobs:
  build-deploy-pr-validation:
    runs-on: ubuntu-latest

    env:
      solution_name: pvaalm
      solution_pack_folder: solution-pack-temp

    steps:
      - uses: actions/checkout@v2

      - name: set environment to pr validation
        run: |
          echo 'environment_url=secrets.UAT_ENV' >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/main')
      
      - name: set environment to uat
        run: |
          echo 'environment_url=secrets.PR_VALIDATION_ENV' >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/main') == false

      - name: pack solution
        uses: microsoft/powerplatform-actions/pack-solution@0.4.3
        with:
          solution-folder: src/${{ env.solution_name }}/SolutionPackage
          solution-file: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ env.solution_name }}.zip
          solution-type: Managed
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.solution_name }}
          path: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ env.solution_name }}.zip
      
      - name: import solution to environment
        uses: microsoft/powerplatform-actions/import-solution@0.4.3
        with:
          environment-url: ${{ env.environment_url }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: ${{ runner.temp }}/${{ env.solution_pack_folder }}/${{ env.solution_name }}.zip
          force-overwrite: true