name: pvaalm-build-deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**
  push:
    branches:
      - main
    paths:
      - src/pvaalm/**

env:
  solution_name: pvaalm
  environmenturl: temp
  build_number: '1.0'

jobs:
  set-github-environment-build-number: # determine if the build should go to the PR or UAT environment
    name: determine deployment environment and generate build number
    runs-on: ubuntu-latest
    
    steps: 
      - name: uat env var
        if: github.ref == 'refs/heads/main'
        run: |
          echo "environment=uat" >> $GITHUB_ENV
      - name: pr env var
        if: github.ref != 'refs/heads/main'
        run: |
          echo "environment=pr" >> $GITHUB_ENV
      - id: setOuput
        run: |
          echo "::set-output name=env::${{ env.environment }}"
          $dateStamp = Get-Date -Format "yyyyMMdd"
          $buildNumber = "${{ env.build_number }}.$dateStamp.${{ github.run_number }}"
          echo "::set-output name=env::${{ env.environment }}"
        shell: pwsh

    outputs:
      environment: ${{ steps.setOuput.outputs.env }}

  build-solution:
    name: build solution
    uses: devkeydet/pva-alm/.github/workflows/build-solution.yml@main
    
    with:
      solution_name: pvaalm # Using env.solution_name was causing the workflow to be invalid. Need to investigate.      
      build_number: "${{ env.build_number }}"   
  
  deploy-solution:
    name: deploy solution to ${{ needs.set-github-environment.outputs.environment }} environment
    uses: devkeydet/pva-alm/.github/workflows/deploy-solution.yml@main
    needs: [set-github-environment, build-solution] 
    with:
      solution_name: pvaalm # Using env.solution_name was causing the workflow to be invalid. Need to investigate.
      environment: ${{ needs.set-github-environment.outputs.environment }}
    secrets:      
      environment_url: ${{ secrets.ENVIRONMENT_URL }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
