name: pvaalm-pr-main-build-deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**
  push:
    branches:
      - main
    paths:
      - src/pvaalm/**

env:
  solution_name: pvaalm
  
jobs:
  build-solution:
    uses: devkeydet/pva-alm/.github/workflows/build-solution.yml@main
    with:
      solution_name: pvaalm
  
  deploy-solution:
    uses: devkeydet/pva-alm/.github/workflows/deploy-solution.yml@main
    needs: build-solution
    with:
      solution_name: pvaalm
    secrets:
      UAT_ENV: ${{ secrets.UAT_ENV }}
      PR_VALIDATION_ENV: ${{ secrets.PR_VALIDATION_ENV }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}