name: pvaalm-pr-build-deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - src/pvaalm/**

env:
  solution_name: pvaalm
  environmenturl: temp

jobs:
  set-env-var-conditionally:
    runs-on: ubuntu-latest
    steps:
      - name: set environment variables conditionally
        shell: pwsh
        run: |
          $ref = '${{ github.ref }}''
          switch ( $ref )
          {
            'refs/heads/main'
            {
              echo 'environment_url=uat' >> $GITHUB_ENV
            }
            default
            {
              echo 'environment_url=pr' >> $GITHUB_ENV
            } 
          }
  echo-env-var-set:
    runs-on: ubuntu-latest
    steps:
      - name: echo env var set
        run: |
          echo '${{ env.environment_url }}'

  build-solution:
    uses: devkeydet/pva-alm/.github/workflows/build-solution.yml@main
    needs: set-env-var-conditionally
    with:
      solution_name: pvaalm # Using env.solution_name was causing the workflow to be invalid. Need to investigate.
  
  deploy-solution:
    uses: devkeydet/pva-alm/.github/workflows/deploy-solution.yml@main
    needs: build-solution
    with:
      solution_name: pvaalm # Using env.solution_name was causing the workflow to be invalid. Need to investigate.
    secrets:      
      environment_url: ${{ secrets.PR_VALIDATION_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
      