name: reusable-whoami

on:
  workflow_call:
    inputs:
      environment_url:
        required: true
        type: string
      tenant_id:
        required: true
        type: string
      client_id:
        required: true
        type: string
      client_secret:
        required: true
        type: string

jobs:
  whoami:
    runs-on: ubuntu-latest

    steps:   
      # comment
      - name: call whoami-action
        uses: microsoft/powerplatform-actions/who-am-i@0.4.3
        with:
          environment-url: ${{ inputs.environment_url }}          
          tenant-id: ${{ inputs.tenant_id }}
          app-id: ${{ inputs.client_id }}
          client-secret: ${{ inputs.client_secret }}