# This is a basic workflow to help you get started with Actions

name: rt

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
    workflow_call:
      secrets:
        secrets:
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
                
      - uses: Firenza/secrets-to-env@v1.1.0
        with:
          secrets: ${{ secrets.secrets) }}

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["src/pvaalm/deploymentSettings.json"]'
