name: rt

on:
  workflow_call:
    secrets:
      secrets:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
                
      - uses: Firenza/secrets-to-env@v1.1.0
        with:
          secrets: ${{ secrets.secrets }}

      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["src/pvaalm/deploymentSettings.json"]'
