name: t

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/turn-on-flows-impersonation
      with:
        secrets: ${{ toJSON(secrets) }}
        files: '["src/pvaalm/deploymentSettings.json"]'
