name: t

on:
  workflow_dispatch:

env:
  environment: prod

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ env.environment }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "${{ env.environment }}"
