# This is a basic workflow to help you get started with Actions

name: temp-another

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Microsoft.Xrm.Data.PowerShell, Microsoft.PowerApps.Administration.PowerShell
          shell: powershell
          
      - name: Show that the Action works on PowerShell
        shell: powershell
        run: |
          Get-Module -Name Microsoft.Xrm.Data.PowerShell, Microsoft.PowerApps.Administration.PowerShell -ListAvailable | Select Path
          Import-Module Microsoft.Xrm.Data.PowerShell
