name: temp-gh-test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:      
      - shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "58" --body "pr validation workflow: XXX"