name: temp-test

on:
  workflow_dispatch:

jobs:  
  turn-on-flows:
    runs-on: windows-latest
    environment: marcsc-alm-demo-dev
    steps:
      - uses: actions/checkout@v2
      - id: turn-on-flows-impersonation
        uses: ./.github/actions/turn-on-flows-impersonation
        with:
          environment_url: https://marcsc-alm-demo-dev.crm.dynamics.com
          solution_name: pvaalm
          tenant_id: ${{ secrets.TENANT_ID }}
          app_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          deployment_settings_file: src/pvaalm/deploymentSettings.json
          secrets: ${{ toJSON(secrets) }}
