name: use-reusable-whoami

on:
  workflow_dispatch:

jobs:

  call-whoami-uat:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    if: startsWith(github.ref, 'refs/heads/main')
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
  
  call-whoami-pr:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    if: startsWith(github.ref, 'refs/heads/main') == false
    secrets:      
      environment_url: ${{ secrets.PR_VALIDATION_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}