name: use-reusable-whoami

on:
  workflow_dispatch:

jobs:

  set-env-var-conditionally:
    runs-on: ubuntu-latest
    outputs:
      environment_url: ${{ steps.set-output.outputs.environment_url }}
    steps: 
      - name: uat env var
        if: startsWith(github.ref, 'refs/heads/main')
        run: |
          echo "environment_url=uat" >> $GITHUB_ENV
      - name: pr env var
        if: startsWith(github.ref, 'refs/heads/main') == false
        run: |
          echo "environment_url=uat" >> $GITHUB_ENV
      - id: set-ouput
        run: |
          echo "::set-output name=environment_url::${{ env.environment_url }}"
      
  echo-env-var-set:
    runs-on: ubuntu-latest
    needs: set-env-var-conditionally
    steps:
      - name: echo env var set in previous job
        run: |
          echo '${{ needs.set-env-var-conditionally.outputs.environment_url }}'

  call-whoami-uat:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    if: startsWith(github.ref, 'refs/heads/main')
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
  
  call-whoami-pr:
    uses: devkeydet/pva-alm/.github/workflows/reusable-whoami.yml@main
    if: startsWith(github.ref, 'refs/heads/main') == false
    secrets:      
      environment_url: ${{ secrets.UAT_ENV }}
      tenant_id: ${{ secrets.TENANT_ID }}
      client_id: ${{ secrets.CLIENT_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}