name: reusable-whoami

on:
  workflow_dispatch:

jobs:
  whoami:
    runs-on: ubuntu-latest

    env:
      environment-url: ${{ secrets.environment_url }}          
      tenant-id: ${{ secrets.tenant_id }}
      app-id: ${{ inputs.client_id }}
      client-secret: ${{ secrets.client_secret }}

    steps:      
      # comment
      - name: call whoami-action
        uses: microsoft/powerplatform-actions/who-am-i@0.4.3
        with:
          environment-url: ${{ secrets.UAT_ENV }}          
          tenant-id: ${{ secrets.TENANT_ID }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}